apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      # TODO does not work: https://github.com/kubernetes-sigs/kind/issues/973
      # enable-admission-plugins: PodSecurityPolicy
